GENERATED = .gitignore package package.tar.gz
LIB_NAMES = wxwidgets

all: package.tar.gz

clean:
	rm -rf $(GENERATED)

.PHONY: all clean

.gitignore: Makefile
	echo '# FILE IS GENERATED BY MAKE - DO NOT EDIT' > $@
	echo '/config.mk' >> $@
	for file in $(GENERATED) ; do \
		echo /$$file >> $@ ; \
	done

package: Makefile $(addprefix build/,$(filter-out glm,$(LIB_NAMES)))
	rm -rf $@
	mkdir $@
	mkdir $@/licenses
	# wxwidgets:
	cp src/wxwidgets/docs/licence.txt $@/licenses/wxwidgets.txt
	#cp build/wxwidgets/OpenAL32$(SHARED_LIBRARY_POSTFIX) $@/

package.tar.gz: Makefile package
	tar czvf $@ -C package .

include config.mk
include src/makefile.mk
include build/makefile.mk
