GENERATED = .gitignore package package.tar.gz
LIB_NAMES = wxwidgets lua wxlua lua-cjson luafilesystem zlib libzip lua-zip luasocket

all: package.tar.gz

clean:
	rm -rf $(GENERATED)

.PHONY: all clean

.gitignore: Makefile
	echo '# FILE IS GENERATED BY MAKE - DO NOT EDIT' > $@
	echo '/config.mk' >> $@
	for file in $(GENERATED) ; do \
		echo /$$file >> $@ ; \
	done

package: Makefile $(addprefix build/,$(LIB_NAMES))
	rm -rf $@
	mkdir $@
	mkdir $@/licenses
	# wxwidgets:
	cp src/wxwidgets/docs/licence.txt $@/licenses/wxwidgets.txt
	cp build/wxwidgets/lib/*$(SHARED_LIBRARY_POSTFIX) $@/
	# lua:
	cp lua-LICENSE.txt $@/licenses/lua.txt
	cp build/lua/src/$(SHARED_LIBRARY_PREFIX)lua52$(SHARED_LIBRARY_POSTFIX) $@/
	cp build/lua/src/lua$(EXECUTABLE_POSTFIX) $@/
	# wxlua:
	cp src/wxlua/docs/licence.txt $@/licenses/wxlua.txt
	cp build/wxlua/bin/$(CMAKE_BUILD_TYPE)/* $@/
	# lua-cjson:
	cp src/lua-cjson/LICENSE $@/licenses/lua-cjson.txt
	cp build/lua-cjson/cjson$(SHARED_LIBRARY_POSTFIX) $@/
	# luafilesystem:
	cp src/luafilesystem/LICENSE $@/licenses/luafilesystem.txt
	cp build/luafilesystem/lfs$(SHARED_LIBRARY_POSTFIX) $@/
	# zlib:
	cp zlib-LICENSE.txt $@/licenses/zlib.txt
	# libzip:
	cp src/libzip/LICENSE $@/licenses/libzip.txt
	cp build/libzip/lib/libzip$(SHARED_LIBRARY_POSTFIX) $@/
	# lua-zip:
	cp -r build/lua-zip/brimworks $@/
	cp lua-zip-LICENSE.txt $@/licenses/lua-zip.txt
	# semver:
	cp src/semver/semver.lua $@/
	# argparse:
	cp src/argparse/src/argparse.lua $@/
	# lanes:
	cp src/lanes/src/lanes.lua $@/
	mkdir $@/lanes
	cp build/lanes/core$(SHARED_LIBRARY_POSTFIX) $@/lanes/
	# StackTracePlus:
	cp src/StackTracePlus/src/StackTracePlus.lua $@/
	# luasocket:
	mkdir $@/mime
	mkdir $@/socket
	cp src/luasocket/src/ltn12.lua $@/
	cp src/luasocket/src/mime.lua  $@/
	cp src/luasocket/src/socket.lua  $@/socket/
	cp src/luasocket/src/ftp.lua     $@/socket/
	cp src/luasocket/src/http.lua    $@/socket/
	cp src/luasocket/src/smtp.lua    $@/socket/
	cp src/luasocket/src/tp.lua      $@/socket/
	cp src/luasocket/src/url.lua     $@/socket/
	cp src/luasocket/src/headers.lua $@/socket/
	cp build/luasocket/mime/core$(SHARED_LIBRARY_POSTFIX) $@/mime/
	cp build/luasocket/socket/core$(SHARED_LIBRARY_POSTFIX) $@/socket/
	# extra:
	cp $(EXTRA_FILES) $@/


package.tar.gz: Makefile package
	tar czvf $@ -C package .

include config.mk
include src/makefile.mk
include build/makefile.mk
