#!/usr/bin/env python2
import re
import sys
import shutil
import os
import os.path
import tempfile
import subprocess

def unpack_archive( archive, destname ):
    tempdir = tempfile.mkdtemp()
    try:
        if re.search('zip$', archive):
            subprocess.check_call(['unzip', '-q', archive, '-d', tempdir])
        elif re.search('tar.*?$', archive):
            subprocess.check_call(['tar', 'xf', archive, '-C', tempdir])
        else:
            raise RuntimeError(archive+' has an unknown archive format.')

        if os.path.exists(destname):
            shutil.rmtree(destname)

        entries = os.listdir(tempdir)
        if len(entries) == 1:
            entrypath = os.path.join(tempdir, entries[0])
            shutil.move(entrypath, destname)
            os.utime(destname, None) # 'touch' destname
        elif len(entries) > 1:
            os.mkdir(destname)
            for entry in entries:
                entrypath = os.path.join(tempdir, entry)
                shutil.move(entrypath, destname)
        else:
            raise RuntimeError('Archive seems to be empty.')
    finally:
        shutil.rmtree(tempdir)

name = sys.argv[1]
url  = sys.argv[2]

archive = re.search('[^/]+$', url).group(0)

subprocess.check_call(['wget', url])
if not os.path.isfile(archive):
    raise RuntimeError(archive+' doesn\'t exist.')

if os.path.isdir(name):
    shutil.rmtree(name)

try:
    unpack_archive(archive, name)
finally:
    os.remove(archive)
